server:
  port: 8000

spring:
  application:
    name: trainer
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/trainer
    username: bradleyspencer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true